version: "3"

services:
  hello1:
    build: .
    image: hello:v0.2
    # volumes:
    #   - hello1-volume:/tmp
    networks:
      - lab3-network

  hello2:
    build: .
    image: hello:v0.2
    # volumes:
    #   - hello2-volume:/tmp
    networks:
      - lab3-network

# volumes:
#   hello1-volume:
#   hello2-volume:

networks:
  lab3-network:
